### PR TITLE
(work in progress) add: ЙЦУКЕН keyboard layout

### PR DESCRIPTION
**Pull request by K0stov**
Hi! Good job on your keyboard heatmap, it's been useful to me. I like that the user can set their own layout.

I've attempted to add the ЙЦУКЕН keyboard layout, used in Russian:
```
ЙЦУКЕНГШЩЗХЪ
ФЫВАПРОЛДЖЭЁ
ЯЧСМИТЬБЮ___
```

The layout spans 12 characters on the top row, so I've extended the grid width from 10 to 12 characters.

There are two problems with this that I haven't yet solved:
- [the heatmap is misaligned beyond the first 10 characters](https://github.com/oha-Ohashi/oha-Ohashi.github.io/assets/26684396/8986a73d-cab1-46a6-972c-277932c589ee). When the 11th character (**Х**) appears in the text, it is instead heatmapped to **Ф** on the home row. 
- the layout cannot be used in Ortho Fall (`2022_1/a_ortho/ortho_typing.html`), because the characters falling are in Latin. The Russian alphabet is as follows: **АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ**

If you have the time, I'd appreciate help with resolving them. Thank you!

### CODE REVIEW

**Comment by oha-Ohashi** [comment]
I'm sorry but I don't have time for this for some reasons. 
Your PR will be accepted because it seems to have no problem, but further approaches like adding Cyrillic alphabets cannot be done.
This project is under MIT license and I want you feel free to modify it and uploading with your domain.

I would wish your happy keyboard life!!
Plus, please let me know about your keyboard projects if you would like!

**Comment by K0stov** [comment]
I believe the issue is located in [heatmap.min.js](https://github.com/oha-Ohashi/oha-Ohashi.github.io/blob/47f08c1823720d5b3ec429b2ae7eff1c8bf32356/2022_1/a_ortho/static/heatmap.min.js). I will try to solve it myself, but I cannot promise anything.

I would recommend you undo this commit for now, since the pull request is only for demonstrative purposes. This currently breaks not only ЙЦУКЕН, but all other layouts. (Try using QWERTY, inputting the character A and [it will instead highlight D](https://github.com/oha-Ohashi/oha-Ohashi.github.io/assets/26684396/793f3b9a-7615-42b4-a8ef-2180d50b5bb8).)

If you find the time to help, it would be excellent. :)

**Comment by oha-Ohashi** [comment]
Thank you a lot for your advice 😃 
This commit has been reverted at #2 .

> If you find the time to help, it would be excellent. :)
It's hard for me to secure time for development for the time being. I wish I could 😭

**Comment by K0stov** [comment]
Fixed in #3, check it out. :)

> Plus, please let me know about your keyboard projects if you would like!

I work as a translator and I'm making a modified version of Colemak Mod-DH for the Serbian language, and this tool helped me immensely. I decided it would be useful to extend it to Russian and Belarusian. I know people who would benefit from it.

**Comment by oha-Ohashi** [comment]
Those words made me very proud 🥲 
I'm so happy😁

**Pull request merged**
